name:                sequence-crdt
version:             0.1.0.0
github:              "richardlaroocque/sequence-crdt"
license:             GPL-3.0
author:              "Richard Larocque"
maintainer:          "richard@r6l7.com"
copyright:           "2018 Richard Larocque"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/richardlarocque/sequence-crdt#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - QuickCheck
  - binary
  - hashable

executables:
  sequence-crdt-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sequence-crdt
    - QuickCheck
    - binary
    - bytestring

tests:
  sequence-crdt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sequence-crdt
    - hspec
    - HUnit
    - QuickCheck
